/** Default module access — mirrors frontend nav.ts (must match API route roles). */
export const DEFAULT_RBAC_MATRIX: Record<string, string[]> = {
  Dashboard: ["admin", "coordinator", "inspector", "estimator", "sales", "engineer", "inventory", "billing", "qa"],
  Sales: ["admin", "sales", "billing", "inventory", "coordinator"],
  "Sales Enquiries": ["admin", "sales", "coordinator", "billing"],
  Customers: ["admin", "coordinator", "estimator", "sales", "billing"],
  Equipment: ["admin", "coordinator", "inspector", "engineer", "inventory", "qa"],
  "Service Tickets": ["admin", "coordinator", "inspector", "estimator", "engineer", "sales", "qa"],
  "Service Requests": ["admin", "coordinator", "inspector", "estimator", "engineer", "sales", "qa"],
  Inspections: ["admin", "coordinator", "inspector", "estimator", "qa"],
  Estimates: ["admin", "coordinator", "estimator", "billing"],
  "Service Jobs": ["admin", "coordinator", "engineer", "qa"],
  /** Projects page reads the jobs API — keep in sync with jobs.routes canRead (minus engineer, who uses Service Jobs). */
  Projects: ["admin", "coordinator", "qa"],
  "Service Catalog": ["admin", "coordinator", "estimator"],
  "Warranty Claims": ["admin", "coordinator", "inspector", "estimator", "engineer", "sales", "billing", "qa"],
  Inventory: ["admin", "inventory", "engineer"],
  "Inventory Items": ["admin", "inventory", "engineer"],
  "Stock Purchase Requests": ["admin", "inventory", "engineer"],
  Suppliers: ["admin", "inventory"],
  Purchase: ["admin", "inventory", "coordinator", "billing"],
  "Supplier RFQs": ["admin", "inventory", "coordinator", "billing"],
  "Purchase Orders": ["admin", "inventory"],
  "Purchase Returns": ["admin", "inventory"],
  "Stock Transfers": ["admin", "inventory"],
  "Stock Locations": ["admin", "inventory"],
  "Stock Ledger": ["admin", "inventory"],
  Billing: ["admin", "billing"],
  Finance: ["admin", "billing"],
  "Expenses & Commissions": ["admin", "billing"],
  Reports: ["admin", "billing", "coordinator"],
  Notifications: ["admin", "coordinator", "inspector", "estimator", "sales", "engineer", "inventory", "billing", "qa"],
  "QR Tracking": ["admin", "coordinator", "inspector", "engineer", "inventory", "qa"],
  "Audit Logs": ["admin"],
  Users: ["admin"],
  "Office Assets": ["admin"],
  "Master Data": ["admin", "coordinator"],
  Settings: ["admin"],
};

export const RBAC_MODULES = Object.keys(DEFAULT_RBAC_MATRIX);

export const RBAC_ROLES = [
  "admin",
  "coordinator",
  "inspector",
  "estimator",
  "sales",
  "engineer",
  "inventory",
  "billing",
  "qa",
] as const;
